use_frameworks!

platform :ios, '9.0'

target 'CharlesTool_Example' do
  pod 'CharlesTool', :path => '../'

  target 'CharlesTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
